### ISSUE TITLE
bootstrap fails with a stack trace if catalog not in a correct format

### ISSUE THREAD

**Issue by mwhahaha** [cloudnull/directord#114]
**Describe the bug**
I messed up the format and forgot the - host designation. When you mess up the schema, it fails with a keyerror. We should probably do some validations (jsonschema?) around this.

``` shell
[stack@undercloud directord]$ directord --debug bootstrap --catalog directord_catalog.yaml --catalog /usr/share/directord/tools/directord-dev-bootstrap-catalog.yaml --key-file /home/stack/.ssh/id_rsa
INFO Loading server information
Traceback (most recent call last):
  File "/usr/bin/directord", line 33, in <module>
    sys.exit(load_entry_point('directord==0.7.3', 'console_scripts', 'directord')())
  File "/usr/lib/python3.6/site-packages/directord/main.py", line 566, in main
    _mixin.bootstrap_cluster()
  File "/usr/lib/python3.6/site-packages/directord/mixin.py", line 625, in bootstrap_cluster
    for s in self.bootstrap_catalog_entry(entry=directord_server):
  File "/usr/lib/python3.6/site-packages/directord/mixin.py", line 398, in bootstrap_catalog_entry
    host=target["host"],
KeyError: 'host'
```

**To Reproduce**
1. Create catalog but mess up the - host option
2. Run bootstrap
3. Fail

**Expected behavior**
A better message indicating syntax failure would be beneficial

**Comment by mwhahaha** [comment]
Also port is a hard requirement

Traceback (most recent call last):
  File "/usr/bin/directord", line 33, in <module>
    sys.exit(load_entry_point('directord==0.7.3', 'console_scripts', 'directord')())
  File "/usr/lib/python3.6/site-packages/directord/main.py", line 566, in main
    _mixin.bootstrap_cluster()
  File "/usr/lib/python3.6/site-packages/directord/mixin.py", line 632, in bootstrap_cluster
    for c in self.bootstrap_catalog_entry(entry=directord_clients):
  File "/usr/lib/python3.6/site-packages/directord/mixin.py", line 402, in bootstrap_catalog_entry
    port=target.get("port", args["port"]),
KeyError: 'port'

**Comment by cloudnull** [comment]
The catalog runner will now validate a host is present and default ssh port to 22 in the event it is undefined. I will look into using json scheme validation in a future iteration.
