### ISSUE TITLE
Remove signal usage to allow parallel execution

### ISSUE THREAD

**Issue by cloudnull** [cloudnull/directord#99]
**Describe the bug**
Running directord within something like task-core, we're able to run in parallel due to the use of signals.

**Additional context**
Error 

``` shell
taskflow.exceptions.WrappedFailure: WrappedFailure: [Failure: ValueError: signal only works in main thread, Failure: ValueError: signal only works in main thread, Failure: ValueError: signal only works in main thread]
```

**Comment by mwhahaha** [comment]
Was seen in task-core when using the parallel executor

```
Traceback (most recent call last):
  File "/usr/bin/task-core", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/task_core/cmd.py", line 124, in main
    result = engines.run(flow, engine="parallel")
  File "/usr/lib/python3.6/site-packages/taskflow/engines/helpers.py", line 162, in run
    engine.run()
  File "/usr/lib/python3.6/site-packages/taskflow/engines/action_engine/engine.py", line 247, in run
    for _state in self.run_iter(timeout=timeout):
  File "/usr/lib/python3.6/site-packages/taskflow/engines/action_engine/engine.py", line 340, in run_iter
    failure.Failure.reraise_if_any(er_failures)
  File "/usr/lib/python3.6/site-packages/taskflow/types/failure.py", line 341, in reraise_if_any
    raise exc.WrappedFailure(failures)
taskflow.exceptions.WrappedFailure: WrappedFailure: [Failure: ValueError: signal only works in main thread, Failure: ValueError: signal only works in main thread, Failure: ValueError: signal only works in main thread]
```
